---
###############################
## Get Blueprint ID         ###
###############################
    - name: Get Blueprint ID from Ravello
      ravello_get_id:
        resource_name: "{{ ravello_blueprint }}"
        resource_type: blueprints
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
      run_once: true
      register: bp
      tags: [ create ]

    - name: Print Blueprint Name
      debug: var=bp.json.name

    - name: Print Blueprint ID
      debug: var=bp.json.id

#####################################################
##  Create multiple application from Blueprint     ##
#####################################################
    - name: Create Applications from Blueprint
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/"
        method: POST
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        validate_certs: no
        status_code: 201
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
        body:
          name: "{{ item.app_name }}"
          description: "App created using Ansible" 
          baseBlueprintId: "{{ bp.json.id }}"
        body_format: json
      run_once: true
      changed_when: true
      ignore_errors: True
      with_items: "{{ ravello_app_list }}"
      register: apps
      tags: [ create ]

###############################
## Get Application ID       ###
###############################
    - name: Get App ID from Ravello for each App
      ravello_get_id:
        resource_name: "{{ item.app_name }}"
        resource_type: applications
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
      run_once: true
      with_items: "{{ ravello_app_list }}"
      register: apps
      tags: [ deploy, fqdn, token, inventory ]

    # - debug: var=apps
    #   run_once: true
    #   tags: [ deploy, debug, fqdn, token ]

#######################################################
##  Deploy Application(s)                            ##
#######################################################
    - name: Deploy Ravello Application(s)
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ item.json.id }}/publish"
        method: POST
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        validate_certs: no
        status_code: 202
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
        body: >
          {
            "preferredRegion": "{{ ravello_deploy_topology_region }}",
            "optimizationLevel": "{{ ravello_deploy_topology_optimization }}",
            "startAllVms": "{{ ravello_deploy_topology_start_all }}"
          }
        body_format: json
      run_once: true
      when: not item.json.published
      ignore_errors: True
      with_items: "{{ apps.results }}"
      register: deploy
      tags: [ deploy ]

#    - name: Print App Names
#      debug: var=item.json.name
#      with_items: "{{ apps.results }}"
########################################
##  Set application Expiration time   ##
########################################
    - name: Set Application Expiration time
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ item.json.id }}/setExpiration"
        method: POST
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
        body: '{  "expirationFromNowSeconds": {{ ravello_expiration_time_min * 60 }} }'
        body_format: json
      run_once: true
      when: not item.json.published
      with_items: "{{ apps.results }}"
      tags: [ deploy ]

###############################
## Get VM ID                ###
###############################
    - name: Get VM ID from Ravello
      ravello_get_id:
        resource_type: vms
        application_id: "{{ item.0.json.id }}"
        resource_name: "{{ item.1.vm_name }}"
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
      with_nested: 
           - "{{ apps.results }}"
           - "{{ ravello_vms_list }}"
      register: vms
      tags: [ fqdn, inventory ]

#    - name: print App IDs (item0)
#      debug: var=item.json.id
#      with_items: "{{ apps.results }}"

#    - name: print VM Names (item1)
#      debug: var=item.vm_name
#      with_items: "{{ ravello_vms_list }}"

###############################
##  Getting Public FQDNs     ##
###############################
    - name: Get VM Public FQDN
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ item.invocation.module_args.application_id }}/vms/{{ item.json.id }}/fqdn;deployment"
        method: GET
        body_format: json
        return_content: yes
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
      with_items: "{{ vms.results }}"
      register: public_fqdn
      tags: [ fqdn, inventory ]

#    - name: Print Application IDs
#      debug: var=item.item.invocation.module_args.application_id
#      with_items: "{{ public_fqdn.results }}"

#######################################
##  Create files with all Labs info  ##
#######################################

    - name: Delete previous App YAML file(s) for Customer "{{ customer_name }}"
      file: path={{ ravello_fqdn_dir }}/{{ item.item.invocation.module_args.application_id }}.yaml state=absent
      tags: [ fqdn ]
      run_once: true
      with_items: "{{ public_fqdn.results }}"

    - name: Add Service Names in App YAML file(s) for Customer "{{ customer_name }}")
      lineinfile:
        dest: "{{ ravello_fqdn_dir }}/{{ item.item.invocation.module_args.application_id }}.yaml"
        line: "{{ item.item.json.description }}:"
        create: yes
      with_items: "{{ public_fqdn.results }}"
      tags: [ fqdn ]

    - name: Create CloudForms Self-Service Portal Service Name in App YAML file(s) for Customer "{{ customer_name }}"
      lineinfile:
        dest: "{{ ravello_fqdn_dir }}/{{ item.item.invocation.module_args.application_id }}.yaml"
        line: "CloudForms Self-Service Portal:"
        create: yes
        insertafter: "^CloudForms Cloud Management Engine Portal:"
      with_items: "{{ public_fqdn.results }}"
      when: item.item.json.description == "CloudForms Cloud Management Engine Portal"
      tags: [ fqdn ]

    - name: Add VM FQDNs and Names in App YAML file(s) for Customer "{{ customer_name }}"
      lineinfile:
        dest: "{{ ravello_fqdn_dir }}/{{ item.item.invocation.module_args.application_id }}.yaml"
        line: "  {{ item.item.invocation.module_args.resource_name  }}: https://{{ item.json.value }}\n"
        create: yes
        insertafter: "^{{ item.item.json.description }}:"
      with_items: "{{ public_fqdn.results }}"
      tags: [ fqdn ]

    - name: Add CloudForms Self-Service FQDN and Name in App YAML file(s) for Customer "{{ customer_name }}"
      lineinfile:
        dest: "{{ ravello_fqdn_dir }}/{{ item.item.invocation.module_args.application_id }}.yaml"
        line: "  CloudForms_UI: https://{{ item.json.value }}/self_service\n"
        create: yes
        insertafter: "^CloudForms Self-Service Portal:"
      with_items: "{{ public_fqdn.results }}"
      when: item.item.invocation.module_args.resource_name == "CloudForms_UI"
      tags: [ fqdn ]

    - name: Rename App YAML files with its App Name for Customer "{{ customer_name }}"
      command: mv "{{ravello_fqdn_dir}}/{{item.json.id}}.yaml" "{{ravello_fqdn_dir}}/{{item.json.name}}.yaml"
      with_items: "{{apps.results}}"
     
    - name: Get App YAML files for Customer "{{ customer_name }}"
      command: ls "{{ravello_fqdn_dir}}" 
      register: app_files

    - name: Print App YAML files for Customer "{{ customer_name }}"
      debug: var=app_files
      
